apiVersion: apps/v1
kind: Deployment
metadata:
  name: clem-process-raw-lifs
  namespace: {{ .Values.global.namespace }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: clem-process-raw-lifs
  template:
    metadata:
      labels:
        app: clem-process-raw-lifs
    spec:
      securityContext:
        runAsUser: {{ .Values.global.runAsUser }}
        runAsGroup: {{ .Values.global.runAsGroup }}
      containers:
      - name: clem-process-raw-lifs-runner
        image: {{ .Values.image }}
        imagePullPolicy: Always
        resources:
          requests:
            cpu: {{ .Values.cpuRequest }}
          limits:
            cpu: {{ .Values.cpuLimit }}
            memory: {{ .Values.memoryLimit }}
        command: ["/bin/sh"]
        args:
          - -c
          - >-
              {{ .Values.command }}
        volumeMounts:
        - name: config-file
          mountPath: /cryoemservices/config
        - name: secrets
          mountPath: /cryoemservices/secrets
        {{- if .Values.global.extraGlobalVolumeMounts }}
        {{- toYaml .Values.global.extraGlobalVolumeMounts | nindent 8 }}
        {{- end }}
        {{- if .Values.extraVolumeMounts }}
        {{- toYaml .Values.extraVolumeMounts | nindent 8 }}
        {{- end }}
      volumes:
      - name: config-file
        configMap:
          name: {{ .Values.global.configMap }}
      - name: secrets
        projected:
          defaultMode: 0444
          sources:
          - secret:
              name: {{ .Values.global.rmqSecretName }}
      {{- if .Values.global.extraGlobalVolumes }}
      {{- toYaml .Values.global.extraGlobalVolumes | nindent 6 }}
      {{- end }}
      {{- if .Values.extraVolumes }}
      {{- toYaml .Values.extraVolumes | nindent 6 }}
      {{- end }}

      {{- if .Values.global.tolerations }}
      tolerations:
        {{- toYaml .Values.global.tolerations | nindent 6 }}
      {{- end }}
      {{- if .Values.global.nodeSelector }}
      nodeSelector:
        {{- toYaml .Values.global.nodeSelector | nindent 8 }}
      {{- end }}
      {{- if .Values.global.imagePullSecrets }}
      imagePullSecrets:
      - name: {{ .Values.global.imagePullSecrets }}
      {{- end }}

{{- if .Values.scaleOnQueueLength }}
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: clem-process-raw-lifs
  namespace: {{ .Values.global.namespace }}
spec:
  scaleTargetRef:
    name: clem-process-raw-lifs
  triggers:
    - type: rabbitmq
      metadata:
        host: {{ .Values.global.rmqHost }}
        queueName: clem.process_raw_lifs
        mode: QueueLength
        value: "{{ .Values.queueLengthTrigger }}"
  minReplicaCount: {{ .Values.minReplicaCount }}
  maxReplicaCount: {{ .Values.maxReplicaCount }}
{{- end }}
