apiVersion: apps/v1
kind: Deployment
metadata:
  name: clem-align-and-merge
  namespace: {{ .Values.global.namespace }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: clem-align-and-merge
  template:
    metadata:
      labels:
        app: clem-align-and-merge
    spec:
      securityContext:
        runAsUser: {{ .Values.global.runAsUser }}
        runAsGroup: {{ .Values.global.runAsGroup }}
      containers:
        - name: clem-align-and-merge-runner
          image: {{ .Values.image }}
          imagePullPolicy: Always
          resources:
            requests:
              cpu: {{ .Values.cpuRequest }}
            limits:
              cpu: {{ .Values.cpuLimit }}
              memory: {{ .Values.memoryLimit }}
          command: ["/bin/sh"]
          args:
            - -c
            - >-
                {{ .Values.command }}
          volumeMounts:
            - name: config-file
              mountPath: /cryoemservices/config
            - name: secrets
              mountPath: /cryoemservices/secrets
            {{- if .Values.global.extraGlobalVolumeMounts }}
            {{- toYaml .Values.global.extraGlobalVolumeMounts | nindent 12 }}
            {{- end }}
            {{- if .Values.extraVolumeMounts }}
            {{- toYaml .Values.extraVolumeMounts | nindent 12 }}
            {{- end }}
      volumes:
        - name: config-file
          configMap:
            name: {{ .Values.global.configMap }}
        - name: secrets
          projected:
            defaultMode: 0444
            sources:
              - secret:
                  name: {{ .Values.global.rmqSecretName }}
        {{- if .Values.global.extraGlobalVolumes }}
        {{- toYaml .Values.global.extraGlobalVolumes | nindent 8 }}
        {{- end }}
        {{- if .Values.extraVolumes }}
        {{- toYaml .Values.extraVolumes | nindent 8 }}
        {{- end }}

      {{- if .Values.global.tolerations }}
      tolerations:
        {{- toYaml .Values.global.tolerations | nindent 8 }}
      {{- end }}
      {{- if .Values.global.nodeSelector }}
      nodeSelector:
        {{- toYaml .Values.global.nodeSelector | nindent 8 }}
      {{- end }}
      {{- if .Values.global.imagePullSecrets }}
      imagePullSecrets:
        - name: {{ .Values.global.imagePullSecrets }}
      {{- end }}

{{- if .Values.scaleOnQueueLength }}
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: clem-align-and-merge
  namespace: {{ .Values.global.namespace }}
spec:
  scaleTargetRef:
    name: clem-align-and-merge
  triggers:
    - type: rabbitmq
      metadata:
        host: {{ .Values.global.rmqHost }}
        queueName: clem.align_and_merge
        mode: QueueLength
        value: "{{ .Values.queueLengthTrigger }}"
  minReplicaCount: {{ .Values.minReplicaCount }}
  maxReplicaCount: {{ .Values.maxReplicaCount }}
{{- end }}
