apiVersion: apps/v1
kind: Deployment
metadata:
  name: membrain-seg
  namespace: {{ .Values.global.namespace }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: membrain-seg
  template:
    metadata:
      labels:
        app: membrain-seg
    spec:
      securityContext:
        runAsUser: {{ .Values.global.runAsUser }}
        runAsGroup: {{ .Values.global.runAsGroup }}
      containers:
      - name: membrain-seg-runner
        image: {{ .Values.image }}
        imagePullPolicy: Always
        resources:
          requests:
            cpu: {{ .Values.cpuRequest }}
          limits:
            cpu: {{ .Values.cpuLimit }}
            memory: {{ .Values.memoryLimit }}
        command: ["/bin/sh"]
        args:
          - -c
          - >-
              {{ .Values.command }}
        env:
        - name: SLURM_RESTAPI_CONFIG
          value: "{{ .Values.slurmCredentials }}"
        volumeMounts:
        - name: config-file
          mountPath: /cryoemservices/config
        - name: secrets
          mountPath: /cryoemservices/secrets
{{- if .Values.extraGlobalVolumeMounts }}
{{ toYaml .Values.extraGlobalVolumeMounts | indent 8 }}
{{ end }}
{{- if .Values.extraVolumeMounts }}
{{ toYaml .Values.extraVolumeMounts | indent 8 }}
{{ end }}
      volumes:
      - name: config-file
        configMap:
          name: {{ .Values.global.configMap }}
      - name: secrets
        projected:
          defaultMode: 0444
          sources:
          - secret:
              name: {{ .Values.global.rmqSecretName }}
          - secret:
              name: {{ .Values.global.rmqApiSecretName }}
{{- if .Values.extraGlobalVolumes }}
{{ toYaml .Values.extraGlobalVolumes | indent 6 }}
{{ end }}
{{- if .Values.extraVolumes }}
{{ toYaml .Values.extraVolumes | indent 6 }}
{{ end }}

{{- if .Values.scaleOnQueueLength }}
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: membrain-seg
  namespace: {{ .Values.global.namespace }}
spec:
  scaleTargetRef:
    name: membrain-seg
  triggers:
    - type: rabbitmq
      metadata:
        host: {{ .Values.global.rmqHost }}
        queueName: segmentation
        mode: QueueLength
        value: "{{ .Values.queueLengthTrigger }}"
  minReplicaCount: {{ .Values.minReplicaCount }}
  maxReplicaCount: {{ .Values.maxReplicaCount }}
{{ end }}
